language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - rust: nightly
cache: cargo
before_script:
  - |
    rustup install nightly &&
    cargo +nightly install rustfmt-nightly --force

script:
  - |
    cargo +nightly fmt -- --check &&
    cargo build &&
    cargo test
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libssl-dev
