[package]
name = "cargo-sphinx"
version = "0.1.0"
authors = ["Ning Sun <sunng@about.me>", "Pascal Hartig <i@passy.me>", "Daithi O Crualaoich <daithi.ocrualaoich@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Cargo subcommand for building and publishing Sphinx documentation to GitHub Pages."
keywords = ["cargo"]
repository = "https://github.com/woofwoofinc/cargo-sphinx"
readme = "README.md"

include = [
    "src/*",
    "AUTHORS",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE-*",
    "README.md",
]

[dependencies]
toml = "0.2.0"
quick-error = "1.1.0"
clap = "2.10.4"
cargo = "0.12.0"
term = "0.4.4"

[package.metadata.sphinx]
docs-path = "docs"
commit-message = "(cargo-sphinx) Generate docs."
sign-commit = false
push-remote = "origin"
push-branch = "gh-pages"
